name: titanic-mlflow-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas==2.2.2
      - scikit-learn==1.4.2
      - matplotlib==3.8.4
